# Generated by Django 5.2.16 on 2026-07-10 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idAdmin', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('tokenExpiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('idController', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('codiceFiscale', models.CharField(max_length=16)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'controllers',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('idRoute', models.BigAutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Durata in minuti')),
                ('departureTime', models.DateTimeField()),
                ('arrivalTime', models.DateTimeField()),
                ('daysOfWeek', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('codiceFiscale', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NOT_VERIFIED', 'Non verificato'), ('ACTIVE', 'Attivo'), ('SUSPENDED', 'Sospeso'), ('DELETED', 'Eliminato')], default='NOT_VERIFIED', max_length=20)),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('tokenExpiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ControllerReport',
            fields=[
                ('idReportController', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aperto'), ('IN_REVIEW', 'In lavorazione'), ('CLOSED', 'Chiuso')], default='OPEN', max_length=20)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllerReports', to='core.controller')),
            ],
            options={
                'db_table': 'controller_reports',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idTicket', models.BigAutoField(primary_key=True, serialize=False)),
                ('purchaseDate', models.DateTimeField()),
                ('expirationDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('VALID', 'Valido'), ('USED', 'Utilizzato'), ('EXPIRED', 'Scaduto')], default='VALID', max_length=20)),
                ('quantitySeats', models.IntegerField()),
                ('qrCodeData', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paymentMethod', models.CharField(choices=[('NEXI', 'Nexi'), ('PAYPAL', 'PayPal')], max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.user')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketInspection',
            fields=[
                ('idInspection', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(choices=[('VALID', 'Valido'), ('INVALID', 'Non valido'), ('EXPIRED', 'Scaduto')], max_length=20)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.controller')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='core.ticket')),
            ],
            options={
                'db_table': 'ticket_inspections',
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('idFine', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='core.ticketinspection')),
            ],
            options={
                'db_table': 'fines',
            },
        ),
        migrations.CreateModel(
            name='GlobalNotification',
            fields=[
                ('idNotification', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('dateSent', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('SERVICE_UPDATE', 'Aggiornamento servizio'), ('MAINTENANCE', 'Manutenzione'), ('MARKETING', 'Marketing'), ('GENERAL', 'Generale')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmata'), ('SENT', 'Inviata'), ('CANCELED', 'Annullata')], default='SCHEDULED', max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.admin')),
                ('controllerRecipients', models.ManyToManyField(blank=True, related_name='notifications', to='core.controller')),
                ('userRecipients', models.ManyToManyField(blank=True, related_name='notifications', to='core.user')),
            ],
            options={
                'db_table': 'global_notifications',
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('idReport', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aperto'), ('IN_REVIEW', 'In lavorazione'), ('CLOSED', 'Chiuso')], default='OPEN', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userReports', to='core.user')),
            ],
            options={
                'db_table': 'user_reports',
            },
        ),
    ]
